### ISSUE TITLE
Parallel implementation of: diff-based metrics, entire commit

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/git-churn#7]
Once we have the functionality of #6 working, let's look for an opportunity to parallelize it across files in a given commit.

Given a commit hash, compute all of the diff-based metrics for each file in parallel. 

I have no idea what Go's concurrency model looks like, so this one will take some research. We might need to start deciding on things like number of threads and whatnot. There will be some exploration here.

**Comment by ashishgalagali** [comment]
https://blog.golang.org/waza-talk
https://www.ardanlabs.com/blog/2014/01/concurrency-goroutines-and-gomaxprocs.html
"Concurrency is about dealing with lots of things at once. Parallelism is about doing lots of things at once."

**Comment by ashishgalagali** [comment]
I implemented go routines wherever I felt the code can be run in parallel while getting the aggregated DiffMetrics for all the files(whitespace included). But as I am going through the diff and doing string operation on it instead of getting the diff metrics individually for all the files to get the aggregated diff metrics (excluding whitespace), I didn't find any code which could be run in parallel.
